# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 900)

        # ---- Central widget + vertical layout --------------------
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")

        # ---- ARM PLOT (square-ish, takes most space) -------------
        self.armPlot = PlotWidget(self.centralwidget)
        self.armPlot.setObjectName("armPlot")
        self.armPlot.setMinimumSize(QtCore.QSize(400, 400))
        self.verticalLayout.addWidget(self.armPlot)

        # ---- ANGLE PLOT (joint angles over time) -----------------
        self.anglePlot = PlotWidget(self.centralwidget)
        self.anglePlot.setObjectName("anglePlot")
        self.anglePlot.setMinimumSize(QtCore.QSize(400, 200))
        self.verticalLayout.addWidget(self.anglePlot)

        # ---- TELEMETRY LABEL -------------------------------------
        self.infoLabel = QtWidgets.QLabel(self.centralwidget)
        self.infoLabel.setObjectName("infoLabel")
        self.infoLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.infoLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.infoLabel.setMinimumHeight(32)
        self.verticalLayout.addWidget(self.infoLabel)

        # ---- Button row ---------------------------------------------
        self.buttonRow = QtWidgets.QHBoxLayout()

        self.spawnButton = QtWidgets.QPushButton("Spawn Object")
        self.spawnButton.setObjectName("spawnButton")
        self.buttonRow.addWidget(self.spawnButton)

        self.pickButton = QtWidgets.QPushButton("Pick")
        self.pickButton.setObjectName("pickButton")
        self.buttonRow.addWidget(self.pickButton)

        self.placeButton = QtWidgets.QPushButton("Place")
        self.placeButton.setObjectName("placeButton")
        self.buttonRow.addWidget(self.placeButton)

        self.verticalLayout.addLayout(self.buttonRow)






        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "3-DOF Arm — Viewer"))
        self.infoLabel.setText(_translate("MainWindow", "Telemetry: waiting…"))


from pyqtgraph import PlotWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())